### ISSUE TITLE
XDR Read Error: Unknown OperationType member for value 24

### ISSUE THREAD

**Issue by rust-master** [stellar/js-soroban-client#125] opened 2023-08-08 12:54 UTC
I'm using the Typescript client and facing an issue on React side when invoking the write function of the contract.

Error:
```
Error: XDR Read Error: Unknown OperationType member for value 24
    at h (contentScript.min.js:1:13535)
(anonymous) @ contentScript.min.js:1
```

Code:
 ```
  let data = await exampleProject.setName(
        {
          value:  "John",
        }
      );

```

**Comment by Shaptic** [comment] 2023-08-14 20:32
Closing as a duplicate of #122.

**Closed by Shaptic** 2023-08-14 20:32 UTC
Labels: bug
