### ISSUE TITLE
Server constructor error in browser v0.7.0

### ISSUE THREAD

**Issue by esteblock** [stellar/js-soroban-client#94] opened 2023-05-25 17:32 UTC
**Describe the bug**
- soroban-client does not works with browser / Client Components
- it did work in v0.5.1

So. I did two experiments:
1) A brand new create-react-app
2) A brand new create-next-app

In both I installed soroban-client 0.7.0. Without installing @soroban-react.

The code added is very simple:

```
import SorobanClient from "soroban-client";
const myServer = new SorobanClient.Server('https://soroban-rpc.stellar.org');
console.log(myServer)
```

With create-react-app: https://github.com/esteblock/create-react-app-soroban-client/tree/soroban-client%400.7.0
With next: https://github.com/esteblock/my-next-app-soroban-client/tree/soroban-client-0.7.0

With both of them I encounter the same error. 

1) With create-react-app I got:
```
Uncaught TypeError: soroban_client__WEBPACK_IMPORTED_MODULE_2___default(...).Server is not a constructor
    at ./src/App.js (App.js:5:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./src/index.js (App.js:29:1)
    at options.factory (react refresh:6:1)
    at __webpack_require__ (bootstrap:24:1)
    at startup:7:1
    at startup:7:1
```

2) With Next:
At the begginig I was not having any problem. But I was not having any console.log in the browser either (Console.log in the console was working fine)
This is because by default, Next.js uses Server Components.
After I added "use client" at the top, to make it a Client Component I got the same problem:

```
Unhandled Runtime Error

TypeError: soroban_client__WEBPACK_IMPORTED_MODULE_1___default().Server is not a constructor
Source

src/app/page.tsx (6:17) @ <unknown>

  4 | import styles from './page.module.css'
  5 | 
> 6 | const myServer = new SorobanClient.Server('https://soroban-rpc.stellar.org');
    |                 ^
  7 | console.log(myServer)
```

So this enforces my theory about webpack changes introduced in https://github.com/stellar/js-soroban-client/compare/v0.5.1...v0.6.0

Should we move to an issue in js-soroban-client?

___

When I install soroban-client@0.5.1 works OK, both with create-react-app and next

https://github.com/esteblock/create-react-app-soroban-client/tree/soroban-client%400.5.1
https://github.com/esteblock/my-next-app-soroban-client/tree/soroban-client%400.5.1

___

**Additional context**
bug reported: https://github.com/esteblock/soroban-react/issues/30 and https://github.com/esteblock/soroban-react/pull/28#issuecomment-1554847236

**Comment by Shaptic** [comment] 2023-05-25 20:19
Thank you for the MWE! This is super helpful and I actually think I just got it fixed. Can you point your projects to this dependency to confirm? cc @piyalbasu as well:

```
"soroban-client": "git+https://github.com/stellar/js-soroban-client#bd463151"
```

**Comment by Shaptic** [comment] 2023-05-25 20:25
Oh wait, this is what actually fixes it:

```diff
- import SorobanClient from 'soroban-client';
+ import * as SorobanClient from 'soroban-client';
```

which means I need to figure out whatever Webpack needs to configure in order to properly export defaults :man_facepalming: or everyone has to migrate to this import method.

**Comment by piyalbasu** [comment] 2023-05-25 20:34
> Oh wait, this is what actually fixes it:
> 
> ```diff
> - import SorobanClient from 'soroban-client';
> + import * as SorobanClient from 'soroban-client';
> ```
> 
> which means I need to figure out whatever Webpack needs to configure in order to properly export defaults 🤦‍♂️ or everyone has to migrate to this import method.


Can confirm that `import * as SorobanClient from 'soroban-client'` works on this new branch. It did not in v7.0.0

`import SorobanClient from 'soroban-client'` does not work on the branch or in v7.0.0

**Comment by Shaptic** [comment] 2023-05-25 21:27
Okay, I just confirmed that your React MWE ([esteblock/create-react-app-soroban-client#soroban-client@0.7.0](https://github.com/esteblock/create-react-app-soroban-client/tree/soroban-client%400.7.0)) works with this diff applied (plus `npm i`, of course):

```diff
diff --git a/package.json b/package.json
index d0c6092..4206826 100644
--- a/package.json
+++ b/package.json
@@ -9,7 +9,7 @@
     "react": "^18.2.0",
     "react-dom": "^18.2.0",
     "react-scripts": "5.0.1",
-    "soroban-client": "^0.7.0",
+    "soroban-client": "git+https://github.com/stellar/js-soroban-client#5b81335e",
     "web-vitals": "^2.1.4"
   },
   "scripts": {
diff --git a/src/App.js b/src/App.js
index c3ed11f..d4abb4c 100644
--- a/src/App.js
+++ b/src/App.js
@@ -1,6 +1,6 @@
 import logo from './logo.svg';
 import './App.css';
-import SorobanClient from 'soroban-client'
+import * as SorobanClient from 'soroban-client'
 
 const myServer = new SorobanClient.Server("https://soroban-rpc.stellar.org")
 console.log("myServer: ", myServer)
```

where 5b81335e is the tail of the fix in #95.

I know this isn't ideal (since you still can't `import SorobanClient ...`), but in the interest of unblocking downstream systems, I'd like to get the partial fix merged & released while continuing to investigate. Please review #95!

**Comment by esteblock** [comment] 2023-05-25 21:31
> Oh wait, this is what actually fixes it:
> 
> ```diff
> - import SorobanClient from 'soroban-client';
> + import * as SorobanClient from 'soroban-client';
> ```
> 
> which means I need to figure out whatever Webpack needs to configure in order to properly export defaults man_facepalming or everyone has to migrate to this import method.

So I already did that test in the create-react-app and my-next-app experiments and did not work...

**Comment by Shaptic** [comment] 2023-05-25 21:33
Did you try the new commit hash? There _were_ some bundling changes necessary in addition to the import change.

**Comment by esteblock** [comment] 2023-05-25 21:37
> Did you try the new commit hash? There _were_ some bundling changes necessary in addition to the import change.

Great! With the new commit hash (https://github.com/esteblock/my-next-app-soroban-client/commit/71e96d4c27e35b722517f3f506a1ae161f1c6b18) & 
- import SorobanClient from 'soroban-client';
+ import * as SorobanClient from 'soroban-client';
(https://github.com/esteblock/my-next-app-soroban-client/commit/e2044954fc3bb244c1e37133a6ee98cda9774a0b)

works!

At least for this my-next-app.
Will check for the library now :)

**Comment by Shaptic** [comment] 2023-05-25 21:38
:tada: thank you for confirming! I'll wait for your next update before I merge & release

**Comment by Shaptic** [comment] 2023-05-25 21:39
This has been quite an arduous lesson in bundler shenanigans, thank you for bearing with me! :lotus_position_man:

**Comment by esteblock** [comment] 2023-05-25 21:52
🥳 However you first said https://github.com/stellar/js-soroban-client/commit/de6a45e9e1eb64b5c8536f7e692388f55bd4073e and #95  is using https://github.com/stellar/js-soroban-client/commit/5b81335ee10f9166fbb10538aac428590c691592

**Comment by Shaptic** [comment] 2023-05-25 21:53
yeah `de6a45e` broke the repo's tests :facepalm: but I tried both and there was no difference. the purpose of `de6a45e` was to try to enable the expected `import SorobanClient from ...` behavior to no avail. I think we're safe!

**Comment by esteblock** [comment] 2023-05-25 21:58
Great! Tested and https://github.com/stellar/js-soroban-client/commit/5b81335ee10f9166fbb10538aac428590c691592 also works!

**Closed** 2023-05-25 22:20 UTC
Labels: bug
